# Adapted from: https://helm.sh/docs/howto/charts_tips_and_tricks/
{{- if and (not (empty .Values.imagePullCredentials.username)) (not (empty .Values.imagePullCredentials.password)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullCredentials.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
