{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "java.fullname" . }}
  labels:
   {{- include "java.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.persistence.storageClassName }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClassName | quote }}
    {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size}}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}