{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: {{ include "java.fullname" . }}
    labels:
        {{- include "java.labels" . | nindent 6 }}
stringData:
        {{- range $key, $val := .Values.secrets }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
        {{- end}}

